commands: add support for 'dnf' package manager
And while we are on it, add some missing configuration for Fedora
distribution up to version 22.

* distconf/fedora-20-i686.yaml: New file.
* distconf/fedora-22-i686.yaml: Likewise.
* distconf/fedora-22-x86_64.yaml: Likewise.
* distconf/fedora-20-x86_64.yaml: Add correct content.
* distconf/lib/general.yaml: Add sbin dir, sort alphabetically.
Create new 'os' keyword.
* distconf/lib/fedora.yaml: Move the distro-specific info under
'os' keyword.
* distconf/lib/rhel.yaml: Likewise. Fix indent.
* distconf/rhel-7-x86_64.yaml: Likewise.
* distconf/fedora-21-i686.yaml: Likewise.
* distconf/fedora-21-x86_64.yaml: Inherit from i686.
* distconf/lib/rpmsystems.yaml: Fix indent, remove redundant
'version' keyword.
* distgen/commands.py (YumPkgManager.binary): New variable.
(YumPkgManager._base_command: Use 'self.binary' to allow easy
inheriting.
(DnfPkgManager): New class.
(Commands.__init__): Handle "dnf" package manager correctly.
* tests/testsuite: Run testsuite for all supported distros.
* tests/pkginstaller/distros: New file, list of distros to run the
'pkginstaller' test case against.
* tests/yum/test.tpl: Renamed to tests/pkginstaller/test.tpl.
* tests/yum/test.exp: Renamed to tests/pkginstaller/test.exp.
* tests/pkginstaller/test.exp: Regenerated.
* tests/yum/test.yaml: Renamed to tests/pkginstaller/test.yaml.

diff --git a/tests/testsuite b/tests/testsuite
--- a/tests/testsuite
+++ b/tests/testsuite
@@ -1,11 +1,11 @@
-#!/bin/sh
+#!/bin/bash
 
 testdir="$(dirname "$(readlink -f "$0")")"
 
 export PATH="$testdir/../${PATH+:$PATH}"
 
 tests="
-    yum
+    pkginstaller
 "
 
 success=:
@@ -20,9 +20,31 @@ for i in $tests; do
     wd="$testdir/$i"
     echo "testing: $wd"
     rm -rf "$wd/test.err" "$wd/test.out" "$wd/test.diff"
-    dg --distro=fedora-21-x86_64.yaml \
-        --instantiate "$wd/test.yaml" "$wd/test.tpl" > "$wd/test.out" \
-        || { fail "test '$i' failed (dg command)'" ; continue ; }
+
+    first=:
+    dg_success=:
+    while read distro ; do
+        outfile="$wd/test.out"
+        if $first; then
+            first=false
+        else
+            echo -e "\n" >> "$outfile"
+        fi
+        echo -e "=== $distro ===\n" >> "$outfile"
+        dg --distro="$distro".yaml \
+                --instantiate "$wd/test.yaml" "$wd/test.tpl" \
+                >> "$outfile"
+        if test $? -ne 0; then
+            dg_success=false
+            break
+        fi
+    done < <(cat "$wd/distros")
+
+    $dg_success || {
+        fail "test '$i' failed (dg command)'"
+        continue
+    }
+
     diff -ruN "$wd/test.exp" "$wd/test.out" > "$wd/test.diff" 2>> "$wd/test.err" \
         || { fail "test '$i' failed (diff)'" ; continue ; }
 done
